version: '3.7'

services:

  kratos-migrate:
    image: tribehealth/kratos:vNext
    environment:
      - DSN=postgres://kratos%40cordico-production-psql-server-lexipol:kratos@cordico-production-psql-server-lexipol.postgres.database.azure.com:5432/kratos
    command: migrate sql postgres://kratos%40cordico-production-psql-server-lexipol:kratos@cordico-production-psql-server-lexipol.postgres.database.azure.com:5432/kratos --config /etc/config/kratos.yml --yes
    volumes:
      -
        type: bind
        source: ./kratos
        target: /etc/config
    networks:
      - cordico-dev

  kratos:
    image: tribehealth/kratos:vNext
    ports:
      - "4433:4433"
      - "4434:4434"
    depends_on:
      - kratos-migrate
      - jaeger
    volumes:
      -
        type: bind
        source: ./kratos
        target: /etc/config
    command: serve -c /etc/config/kratos.yml
    networks:
      - cordico-dev
    environment:
      - SERVE_PUBLIC_BASE_URL=https://kratos-ss-dev.dev.cordico.com/.ory/kratos/public/
      - TRACING_PROVIDER=jaeger
      - TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling
      - TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS=jaeger:6831
      - TRACING_PROVIDER_JAEGER_SAMPLING_TYPE=const
      - TRACING_PROVIDER_JAEGER_SAMPLING_VALUE=1
      - DSN=postgres://kratos%40cordico-production-psql-server-lexipol:kratos@cordico-production-psql-server-lexipol.postgres.database.azure.com:5432/kratos

  oathkeeper:
    image: oryd/oathkeeper:v0.38.12-beta.1
    depends_on:
      - jaeger
    networks:
      - cordico-dev
    ports:
      - "4455:4455"
      - "4456:4456"
    command:
      serve proxy --config=/etc/config/oathkeeper/config.yaml
    environment:
      - TRACING_PROVIDER=jaeger
      - TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling
      - TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS=jaeger:6831
      - TRACING_PROVIDER_JAEGER_SAMPLING_TYPE=const
      - TRACING_PROVIDER_JAEGER_SAMPLING_VALUE=1
    volumes:
      - type: bind
        source: ./oathkeeper_config
        target: /etc/config/oathkeeper
    restart: on-failure

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.7.3-alpha.1
    depends_on:
      - kratos
      - oathkeeper
    environment:
      - PORT=6666
      - KRATOS_PUBLIC_URL=https://kratos-ss-dev.dev.cordico.com/.ory/kratos/public
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - KRATOS_BROWSER_URL=https://kratos-ss-dev.dev.cordico.com/.ory/kratos/public
      - JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
      - SECURITY_MODE=jwt
    ports:
      - "6666:6666"
    networks:
      - cordico-dev
    restart: on-failure

  prisma:
    image: tribehealth/prisma-query-engine:v0.0.3
    environment:
      PRISMA_DML_PATH: "/usr/src/app/prisma/schema.prisma"
    volumes:
      - ./prisma/schema.prisma:/usr/src/app/prisma/schema.prisma
    ports:
      - "4466:4466"
    networks:
      - cordico-dev

  user-server:
    image: tribehealth/cordico-user-server:v0.0.41
    ports:
     - "8460:8457"
    depends_on:
    - prisma
    - jaeger
    - ipfs
    - redis
    restart: always
    environment:
      PRISMA_URL: http://prisma:4466
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_APPLICATION_NAME: "cordico-user-service"
      IPFS_HOST: /dns4/ipfs/tcp/5001
      IPFS_URL: https://ipfs.tribecore.io
      KRATOS_URL: http://kratos:4433
      HASURA_URL: http://graphql-engine/v1/graphql
    networks:
      - cordico-dev

  redis:
    image: redis:latest
    ports:
      - 6377:6379
    networks:
      - cordico-dev

  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "4101:4001"
      - "5111:5001"
      - "8181:8080"
    volumes:
      - ./ipfs:/data/ipfs
    networks:
      - cordico-dev

  jaeger:
    image: jaegertracing/all-in-one:1.25
    environment:
      SPAN_STORAGE_TYPE: "badger"
      BADGER_EPHEMERAL: "false"
      BADGER_DIRECTORY_VALUE: "/badger/data"
      BADGER_DIRECTORY_KEY: "/badger/key"
    volumes:
      - ./badger:/badger
    networks:
      - cordico-dev
    ports:
      - "9091:16686"

networks:
  cordico-dev:
    external: true 
